apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodedaemons.app.example.com
spec:
  group: app.example.com
  names:
    kind: NodeDaemon
    listKind: NodeDaemonList
    plural: nodedaemons
    singular: nodedaemon
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: NodeDaemon is the Schema for the nodedaemons API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NodeDaemonSpec defines the desired state of NodeDaemon
          properties:
            image:
              type: string
            label:
              type: string
          required:
          - image
          - label
          type: object
        status:
          description: NodeDaemonStatus defines the observed state of NodeDaemon
          properties:
            count:
              format: int32
              type: integer
          required:
          - count
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
