apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeapp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: timeapp-operator
  template:
    metadata:
      labels:
        name: timeapp-operator
    spec:
      serviceAccountName: timeapp-operator
      containers:
        - name: timeapp-operator
          # Replace this with the built image name
          image: docker.io/vaishnavihire/timeapp-operator:upd11
          command:
          - timeapp-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "timeapp-operator"
